// <auto-generated />
using System;
using LotoSpain_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LotoSpain_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240318082220_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LotoSpain_API.Modelos.Bonoloto", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<string>("combinacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("complementario")
                        .HasColumnType("int");

                    b.Property<int>("reintegro")
                        .HasColumnType("int");

                    b.HasKey("fecha");

                    b.ToTable("bonoloto_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Bote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cuantia")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("jornada")
                        .HasColumnType("int");

                    b.Property<string>("sorteo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("botes_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Eurodreams", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<string>("combinacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("suenho")
                        .HasColumnType("int");

                    b.HasKey("fecha");

                    b.ToTable("eurodreams_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Euromillones", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<string>("combinacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estrellas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fecha");

                    b.ToTable("euromillones_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Gordo", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<int>("clave")
                        .HasColumnType("int");

                    b.Property<string>("combinacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fecha");

                    b.ToTable("gordo_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Lototurf", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<int>("caballo")
                        .HasColumnType("int");

                    b.Property<string>("combinacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("jornada")
                        .HasColumnType("int");

                    b.Property<int>("reintegro")
                        .HasColumnType("int");

                    b.HasKey("fecha");

                    b.ToTable("lototurf_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Nacional", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<string>("combinacion1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("combinacion2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreExtra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reintegros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fecha");

                    b.ToTable("nacional_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Partido", b =>
                {
                    b.Property<string>("local")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Quinielafecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Quinigolfecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("restultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("visitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("local");

                    b.HasIndex("Quinielafecha");

                    b.HasIndex("Quinigolfecha");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Primitiva", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<string>("combinacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("complementario")
                        .HasColumnType("int");

                    b.Property<int>("reintegro")
                        .HasColumnType("int");

                    b.HasKey("fecha");

                    b.ToTable("primitiva_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Quiniela", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("jornada")
                        .HasColumnType("int");

                    b.HasKey("fecha");

                    b.ToTable("quiniela_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Quinigol", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("jornada")
                        .HasColumnType("int");

                    b.HasKey("fecha");

                    b.ToTable("quinigol_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Quintuple", b =>
                {
                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("bote")
                        .HasColumnType("int");

                    b.Property<string>("combinacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("jornada")
                        .HasColumnType("int");

                    b.HasKey("fecha");

                    b.ToTable("quintuple_res");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Partido", b =>
                {
                    b.HasOne("LotoSpain_API.Modelos.Quiniela", null)
                        .WithMany("partidos")
                        .HasForeignKey("Quinielafecha");

                    b.HasOne("LotoSpain_API.Modelos.Quinigol", null)
                        .WithMany("partidos")
                        .HasForeignKey("Quinigolfecha");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Quiniela", b =>
                {
                    b.Navigation("partidos");
                });

            modelBuilder.Entity("LotoSpain_API.Modelos.Quinigol", b =>
                {
                    b.Navigation("partidos");
                });
#pragma warning restore 612, 618
        }
    }
}
